ServerEvents.recipes(event => {
  
  const F = (id, mb) => Fluid.of(id, mb);

    event.recipes.gtceu.assembler('ev_moter')
    .itemInputs('4x gtceu:aluminium_octal_cable','8x gtceu:long_titanium_rod',
        '4x gtceu:magnetic_neodymium_rod','6x gtceu:kanthal_octal_wire')
    .inputFluids('gtceu:advanced_soldering_alloy 144')
    .itemOutputs('gtceu:ev_electric_motor')
    .EUt(512)
    .duration(200)

    event.recipes.gtceu.assembler('ev_conveyor')
    .itemInputs('2x gtceu:aluminium_octal_cable','4x gtceu:ev_electric_motor',)
    .itemInputs(Item.of('gtceu:programmed_circuit', '{Configuration:1}'))
    .inputFluids('gtceu:advanced_soldering_alloy 144')
    .itemOutputs('gtceu:ev_conveyor_module')
    .EUt(512)
    .duration(180)

    event.recipes.gtceu.assembler('ev_pump')
    .itemInputs('4x gtceu:aluminium_octal_cable','2x gtceu:titanium_huge_fluid_pipe','16x gtceu:stainless_steel_screw',Item.of('3x gtceu:turbine_rotor', '{GT.PartStats:{Material:"gtceu:stainless_steel"}}'),'5x gtceu:styrene_butadiene_rubber_ring','3x gtceu:ev_electric_motor')
    .notConsumable(Item.of('gtceu:programmed_circuit', '{Configuration:1}'))
    .inputFluids('gtceu:advanced_soldering_alloy 144')
    .itemOutputs('gtceu:ev_electric_pump')
    .EUt(512)
    .duration(140)

    event.recipes.gtceu.assembler('ev_regulator')
    .itemInputs('4x gtceu:ev_electric_pump','4x #gtceu:circuits/ev')
    .notConsumable(Item.of('gtceu:programmed_circuit', '{Configuration:1}'))
    .inputFluids('gtceu:advanced_soldering_alloy 144')
    .itemOutputs('gtceu:ev_fluid_regulator')
    .EUt(512)
    .duration(160)

    event.recipes.gtceu.assembler('ev_robot_arm')
    .itemInputs('2x gtceu:aluminium_octal_cable','6x gtceu:long_titanium_rod','4x gtceu:ev_electric_motor','2x gtceu:ev_electric_piston','5x #gtceu:circuits/ev')
    .notConsumable(Item.of('gtceu:programmed_circuit', '{Configuration:1}'))
    .inputFluids('gtceu:advanced_soldering_alloy 144')
    .itemOutputs('gtceu:ev_robot_arm')
    .EUt(512)
    .duration(220)

    event.recipes.gtceu.assembler('ev_piston')
    .itemInputs('4x gtceu:long_titanium_rod','12x gtceu:aluminium_octal_cable','4x gtceu:double_titanium_plate','4x gtceu:titanium_gear','6x gtceu:ev_electric_motor')
    .inputFluids('gtceu:advanced_soldering_alloy 144')
    .itemOutputs('gtceu:ev_electric_piston')
    .EUt(512)
    .duration(60)

     event.recipes.gtceu.assembler('ev_field')
    .itemInputs('32x minecraft:nether_star','16x ae2:singularity','32x gtceu:double_titanium_plate','12x #gtceu:circuits/ev','8x gtceu:uranium_triplatinum_octal_wire')
    .inputFluids('gtceu:advanced_soldering_alloy 144')
    .itemOutputs('gtceu:ev_field_generator')
    .EUt(2048)
    .duration(60)

    event.recipes.gtceu.assembler('ev_sensor')
    .itemInputs('12x gtceu:long_platinum_rod','8x gtceu:double_titanium_plate','4x #gtceu:circuits/ev','4x gtceu:quantum_eye')
    .inputFluids('gtceu:advanced_soldering_alloy 144')
    .itemOutputs('gtceu:ev_sensor')
    .EUt(2048)
    .duration(280)

    event.recipes.gtceu.assembler('ev_emitter')
    .itemInputs('12x gtceu:long_platinum_rod','8x gtceu:double_titanium_plate','4x #gtceu:circuits/ev','4x gtceu:quantum_eye')
    .notConsumable(Item.of('gtceu:programmed_circuit', '{Configuration:1}'))
    .inputFluids('gtceu:advanced_soldering_alloy 144')
    .itemOutputs('gtceu:ev_emitter')
    .EUt(2048)
    .duration(280)

    event.recipes.gtceu.assembler('ev_casing')
    .itemInputs('9x gtceu:titanium_plate','gtceu:titanium_frame')
    .inputFluids('gtceu:advanced_soldering_alloy 144',)
    .itemOutputs('gtceu:ev_machine_casing')
    .EUt(512)
    .duration(300)
    
    event.recipes.gtceu.assembler('rtm_coil')
    .itemInputs('8x gtceu:rtm_alloy_hex_wire','16x gtceu:vanadium_steel_foil','4x gtceu:uranium_triplatinum_octal_wire')
    .inputFluids('gtceu:nichrome 144')
    .itemOutputs('gtceu:kanthal_coil_block')
    .EUt(2048)
    .duration(80)

    event.recipes.gtceu.bender('titanium_plate')
    .notConsumable(Item.of('gtceu:programmed_circuit', '{Configuration:1}'))
    .itemInputs('2x gtceu:titanium_ingot')
    .itemOutputs('gtceu:titanium_plate')
    .EUt(450)
    .duration(60)

    event.recipes.gtceu.alloy_blast_smelter('asa')
    .itemInputs('9x gtceu:soldering_alloy_dust','6x gtceu:antimony_dust','3x gtceu:silver_dust','4x ae2:singularity')
    .notConsumable(Item.of('gtceu:programmed_circuit', '{Configuration:10}'))
    .outputFluids('gtceu:advanced_soldering_alloy 432')
    .EUt(1024)
    .duration(700)
    .blastFurnaceTemp(3700)
    
})