ServerEvents.recipes(event => {
  
  const F = (id, mb) => Fluid.of(id, mb);

    event.recipes.gtceu.assembler('hv_motor')
    .itemInputs('4x gtceu:silver_quadruple_cable','2x gtceu:long_stainless_steel_rod',
        '3x gtceu:magnetic_steel_rod','4x gtceu:electrum_hex_wire','2x gtceu:mv_electric_motor')
    .inputFluids('gtceu:soldering_alloy 144')
    .itemOutputs('gtceu:hv_electric_motor')
    .EUt(128)
    .duration(700)

    event.recipes.gtceu.assembler('hv_conveyor')
    .itemInputs('gtceu:gold_hex_cable','2x gtceu:hv_electric_motor','2x gtceu:mv_conveyor_module')
    .itemInputs(Item.of('gtceu:programmed_circuit', '{Configuration:1}'))
    .inputFluids('gtceu:soldering_alloy 144')
    .itemOutputs('gtceu:hv_conveyor_module')
    .EUt(128)
    .duration(700)

    event.recipes.gtceu.assembler('hv_pump')
    .itemInputs('2x gtceu:gold_hex_cable','gtceu:stainless_steel_large_fluid_pipe','3x gtceu:steel_screw','4x gtceu:steel_rotor','5x gtceu:silicone_rubber_ring','3x gtceu:hv_electric_motor','2x gtceu:mv_electric_pump')
    .notConsumable(Item.of('gtceu:programmed_circuit', '{Configuration:1}'))
    .inputFluids('gtceu:soldering_alloy 144')
    .itemOutputs('gtceu:hv_electric_pump')
    .EUt(128)
    .duration(700)

    event.recipes.gtceu.assembler('hv_regulator')
    .itemInputs('3x gtceu:hv_electric_pump','4x #gtceu:circuits/hv','2x gtceu:mv_fluid_regulator')
    .notConsumable(Item.of('gtceu:programmed_circuit', '{Configuration:1}'))
    .inputFluids('gtceu:soldering_alloy 144')
    .itemOutputs('gtceu:hv_fluid_regulator')
    .EUt(128)
    .duration(700)

    event.recipes.gtceu.assembler('hv_robot_arm')
    .itemInputs('6x gtceu:gold_hex_cable','4x gtceu:long_stainless_steel_rod','4x gtceu:hv_electric_motor','3x gtceu:hv_electric_piston','5x #gtceu:circuits/hv','2x gtceu:mv_robot_arm')
    .notConsumable(Item.of('gtceu:programmed_circuit', '{Configuration:1}'))
    .inputFluids('gtceu:soldering_alloy 144')
    .itemOutputs('gtceu:hv_robot_arm')
    .EUt(128)
    .duration(700)

    event.recipes.gtceu.assembler('hv_piston')
    .itemInputs('4x gtceu:long_stainless_steel_rod','2x gtceu:gold_hex_cable','4x gtceu:stainless_steel_plate','4x gtceu:stainless_steel_gear','4x gtceu:hv_electric_motor','2x gtceu:mv_electric_piston',)
    .notConsumable(Item.of('gtceu:programmed_circuit', '{Configuration:1}'))
    .inputFluids('gtceu:soldering_alloy 144')
    .itemOutputs('gtceu:hv_electric_piston')
    .EUt(128)
    .duration(700)

     event.recipes.gtceu.assembler('hv_field')
    .itemInputs('16x gtceu:quantum_eye','6x gtceu:double_stainless_steel_plate','4x #gtceu:circuits/hv','16x gtceu:mercury_barium_calcium_cuprate_hex_wire','16x gtceu:exquisite_amethyst_gem')
    .inputFluids('gtceu:soldering_alloy 144')
    .itemOutputs('gtceu:hv_field_generator')
    .EUt(512)
    .duration(700)

    event.recipes.gtceu.assembler('hv_sensor')
    .itemInputs('4x gtceu:chromium_rod','4x gtceu:double_stainless_steel_plate','2x #gtceu:circuits/hv','3x gtceu:exquisite_emerald_gem','16x minecraft:ender_eye','2x gtceu:mv_sensor')
    .inputFluids('gtceu:soldering_alloy 144')
    .itemOutputs('gtceu:hv_sensor')
    .EUt(128)
    .duration(700)

    event.recipes.gtceu.assembler('hv_emitter')
    .itemInputs('4x gtceu:chromium_rod','4x gtceu:double_stainless_steel_plate','2x #gtceu:circuits/hv','3x gtceu:exquisite_emerald_gem','16x minecraft:ender_eye','2x gtceu:mv_emitter')
    .inputFluids('gtceu:soldering_alloy 144')
    .notConsumable(Item.of('gtceu:programmed_circuit', '{Configuration:1}'))
    .itemOutputs('gtceu:hv_emitter')
    .EUt(128)
    .duration(700)

    event.recipes.gtceu.assembler('hv_casing')
    .itemInputs('4x gtceu:mv_machine_casing','8x gtceu:double_aluminium_plate')
    .inputFluids('gtceu:soldering_alloy 144',)
    .itemOutputs('gtceu:hv_machine_casing')
    .EUt(128)
    .duration(300)
    
    event.recipes.gtceu.assembler('nichrome_coil')
    .itemInputs('2x gtceu:kanthal_coil_block','8x gtceu:nichrome_hex_wire','16x gtceu:stainless_steel_foil')
    .inputFluids('gtceu:aluminium 144')
    .itemOutputs('gtceu:nichrome_coil_block')
    .EUt(512)
    .duration(1000)

    event.recipes.gtceu.assembler('cleanroom')
    .itemInputs('32x gtceu:item_filter','48x gtceu:stainless_steel_rotor','4x gtceu:hv_machine_hull','24x gtceu:hv_electric_motor','16x #gtceu:circuits/hv')
    .inputFluids('gtceu:aluminium 144')
    .itemOutputs('gtceu:cleanroom')
    .EUt(512)
    .duration(6000)

    event.recipes.gtceu.mixer('stainless_steel_dust')
    .itemInputs('8x gtceu:iron_dust','3x gtceu:nickel_dust','2x gtceu:manganese_dust','3x gtceu:chromium_dust')
    .notConsumable(Item.of('gtceu:programmed_circuit', '{Configuration:3}'))
    .itemOutputs('9x gtceu:stainless_steel_dust')
    .EUt(128)
    .duration(400)

    event.recipes.gtceu.electric_blast_furnace('moly_dust')
    .itemInputs('gtceu:molybdenum_dust')
    .itemOutputs('gtceu:molybdenum_ingot')
    .EUt(824)
    .duration(1005)
    .blastFurnaceTemp(1980)

    event.recipes.gtceu.bender('stainless_plate')
    .notConsumable(Item.of('gtceu:programmed_circuit', '{Configuration:1}'))
    .itemInputs('2x gtceu:stainless_steel_ingot')
    .itemOutputs('gtceu:stainless_steel_plate')
    .EUt(128)
    .duration(60)


})