ServerEvents.recipes(event => {
  
  const F = (id, mb) => Fluid.of(id, mb);

    event.recipes.gtceu.assembler('mv_moter')
    .itemInputs('gtceu:copper_quadruple_cable','2x gtceu:long_aluminium_rod',
        '3x gtceu:magnetic_steel_rod','4x gtceu:long_cupronickel_rod')
    .inputFluids('gtceu:soldering_alloy 144')
    .itemOutputs('gtceu:mv_electric_motor')
    .EUt(16)
    .duration(200)

    event.recipes.gtceu.assembler('mv_conveyor')
    .itemInputs('gtceu:copper_quadruple_cable','2x gtceu:mv_electric_motor',)
    .itemInputs(Item.of('gtceu:programmed_circuit', '{Configuration:1}'))
    .inputFluids('gtceu:soldering_alloy 144')
    .itemOutputs('gtceu:mv_conveyor_module')
    .EUt(32)
    .duration(180)

    event.recipes.gtceu.assembler('mv_pump')
    .itemInputs('2x gtceu:copper_quadruple_cable','gtceu:steel_large_fluid_pipe','3x gtceu:bronze_screw','4x gtceu:bronze_rotor','5x gtceu:styrene_butadiene_rubber_ring','3x gtceu:mv_electric_motor')
    .notConsumable(Item.of('gtceu:programmed_circuit', '{Configuration:1}'))
    .inputFluids('gtceu:soldering_alloy 144')
    .itemOutputs('gtceu:mv_electric_pump')
    .EUt(32)
    .duration(140)

    event.recipes.gtceu.assembler('mv_regulator')
    .itemInputs('3x gtceu:mv_electric_pump','4x #gtceu:circuits/mv')
    .notConsumable(Item.of('gtceu:programmed_circuit', '{Configuration:1}'))
    .inputFluids('gtceu:soldering_alloy 144')
    .itemOutputs('gtceu:mv_fluid_regulator')
    .EUt(32)
    .duration(160)

    event.recipes.gtceu.assembler('mv_robot_arm')
    .itemInputs('2x gtceu:copper_quadruple_cable','2x gtceu:long_aluminium_rod','3x gtceu:mv_electric_motor','gtceu:mv_electric_piston','2x #gtceu:circuits/mv')
    .notConsumable(Item.of('gtceu:programmed_circuit', '{Configuration:1}'))
    .inputFluids('gtceu:soldering_alloy 144')
    .itemOutputs('gtceu:mv_robot_arm')
    .EUt(32)
    .duration(220)

    event.recipes.gtceu.assembler('mv_piston')
    .itemInputs('2x gtceu:long_aluminium_rod','2x gtceu:copper_quadruple_cable','4x gtceu:aluminium_plate','2x gtceu:aluminium_gear','2x gtceu:mv_electric_motor')
    .notConsumable(Item.of('gtceu:programmed_circuit', '{Configuration:1}'))
    .inputFluids('gtceu:soldering_alloy', 0.144,)
    .itemOutputs('gtceu:mv_electric_piston')
    .EUt(32)
    .duration(60)

     event.recipes.gtceu.assembler('mv_field')
    .itemInputs('16x minecraft:ender_eye','6x gtceu:double_aluminium_plate','4x #gtceu:circuits/mv','6x gtceu:magnesium_diboride_hex_wire','16x gtceu:exquisite_amethyst_gem')
    .inputFluids('gtceu:soldering_alloy 144')
    .itemOutputs('gtceu:mv_field_generator')
    .EUt(128)
    .duration(60)

    event.recipes.gtceu.assembler('mv_sensor')
    .itemInputs('2x gtceu:long_electrum_rod','3x gtceu:copper_quadruple_cable','2x #gtceu:circuits/mv','3x gtceu:exquisite_emerald_gem')
    .inputFluids('gtceu:soldering_alloy', 0.144,)
    .itemOutputs('gtceu:mv_sensor')
    .EUt(32)
    .duration(280)

    event.recipes.gtceu.assembler('mv_emitter')
    .itemInputs('2x gtceu:long_electrum_rod','3x gtceu:copper_quadruple_cable','2x #gtceu:circuits/mv','3x gtceu:exquisite_emerald_gem')
    .inputFluids('gtceu:soldering_alloy 144')
    .notConsumable(Item.of('gtceu:programmed_circuit', '{Configuration:1}'))
    .itemOutputs('gtceu:mv_emitter')
    .EUt(32)
    .duration(280)

    event.recipes.gtceu.assembler('mv_casing')
    .itemInputs('4x gtceu:lv_machine_casing','8x gtceu:double_aluminium_plate')
    .inputFluids('gtceu:soldering_alloy 144',)
    .itemOutputs('gtceu:mv_machine_casing')
    .EUt(32)
    .duration(300)
    
    event.recipes.gtceu.assembler('kanthal_coil')
    .itemInputs('8x gtceu:kanthal_hex_wire','16x gtceu:aluminium_foil')
    .inputFluids('gtceu:copper 144')
    .itemOutputs('gtceu:kanthal_coil_block')
    .EUt(128)
    .duration(80)

    event.recipes.gtceu.bender('aluminium_plate')
    .notConsumable(Item.of('gtceu:programmed_circuit', '{Configuration:1}'))
    .itemInputs('2x gtceu:aluminium_ingot')
    .itemOutputs('gtceu:aluminium_plate')
    .EUt(32)
    .duration(60)

})