
#Adjustment of the capacity of the machine's internal tank
[Mekanism_Extras]

	[Mekanism_Extras."ExtrasCompressing, Extrasinjecting, Extraspurifying"]
		#Chemical tank capacity (mB). Default: 2541000, Vanilla: 25410
		#Range: 1 ~ 9223372036854775807
		absoluteChemicalTankCapacity = 2541000
		#Chemical tank capacity (mB). Default: 3549000, Vanilla: 35490
		#Range: 1 ~ 9223372036854775807
		supremeChemicalTankCapacity = 3549000
		#Chemical tank capacity (mB) Default: 4725000, Vanilla: 47250
		#Range: 1 ~ 9223372036854775807
		cosmicChemicalTankCapacity = 4725000
		#Chemical tank capacity (mB). Default: 6069000, Vanilla: 60690
		#Range: 1 ~ 9223372036854775807
		infiniteChemicalTankCapacity = 6069000

	[Mekanism_Extras.InfusingFactoryExtras]
		#Chemical tank capacity (mB). Default: 12100000, Vanilla: 121000
		#Range: 1 ~ 9223372036854775807
		absoluteChemicalTankCapacity = 12100000
		#Chemical tank capacity (mB). Default: 16900000, Vanilla: 169000
		#Range: 1 ~ 9223372036854775807
		supremeChemicalTankCapacity = 16900000
		#Chemical tank capacity (mB). Default: 22500000, Vanilla: 225000
		#Range: 1 ~ 9223372036854775807
		cosmicChemicalTankCapacity = 22500000
		#Chemical tank capacity (mB). Default: 28900000, Vanilla: 289000
		#Range: 1 ~ 9223372036854775807
		infiniteChemicalTankCapacity = 28900000

	[Mekanism_Extras.AdvancedElectricPump]
		#Fluid tank capacity (mB). Default: 1000000000, Vanilla: 10000000
		#Range: > 1
		fluidTankCapacity = 1000000000

